"""
combinations, permutattions e product - itertools
combinação - ordem nao importa 
permutação - ordem importa
ambos nao repetem valores unicos
prodict - ordem importa e repetem valores unicos
"""

from itertools import combinations, permutations, product, count

pessoas = ['joao', 'jose', 'luiz', 'andre',
           'eduardo', 'leticia', 'fabricio', 'moises']
print("\nCombinações:")
for grupo in combinations(pessoas, 2):
    print(grupo)
print("\nPermutações:")
for grupo in permutations(pessoas, 2):
    print(grupo)
print("\nProduto:")
for grupo in product(pessoas, repeat=2):
    print(grupo)

# Combinações:
# ('joao', 'jose')
# ('joao', 'luiz')
# ('joao', 'andre')
# ('joao', 'eduardo')
# ('joao', 'leticia')
# ('joao', 'fabricio')
# ('joao', 'moises')
# ('jose', 'luiz')
# ('jose', 'andre')
# ('jose', 'eduardo')
# ('jose', 'leticia')
# ('jose', 'fabricio')
# ('jose', 'moises')
# ('luiz', 'andre')
# ('luiz', 'eduardo')
# ('luiz', 'leticia')
# ('luiz', 'fabricio')
# ('luiz', 'moises')
# ('andre', 'eduardo')
# ('andre', 'leticia')
# ('andre', 'fabricio')
# ('andre', 'moises')
# ('eduardo', 'leticia')
# ('eduardo', 'fabricio')
# ('eduardo', 'moises')
# ('leticia', 'fabricio')
# ('leticia', 'moises')
# ('fabricio', 'moises')

# Permutações:
# ('joao', 'jose')
# ('joao', 'luiz')
# ('joao', 'andre')
# ('joao', 'eduardo')
# ('joao', 'leticia')
# ('joao', 'fabricio')
# ('joao', 'moises')
# ('jose', 'joao')
# ('jose', 'luiz')
# ('jose', 'andre')
# ('jose', 'eduardo')
# ('jose', 'leticia')
# ('jose', 'fabricio')
# ('jose', 'moises')
# ('luiz', 'joao')
# ('luiz', 'jose')
# ('luiz', 'andre')
# ('luiz', 'eduardo')
# ('luiz', 'leticia')
# ('luiz', 'fabricio')
# ('luiz', 'moises')
# ('andre', 'joao')
# ('andre', 'jose')
# ('andre', 'luiz')
# ('andre', 'eduardo')
# ('andre', 'leticia')
# ('andre', 'fabricio')
# ('andre', 'moises')
# ('eduardo', 'joao')
# ('eduardo', 'jose')
# ('eduardo', 'luiz')
# ('eduardo', 'andre')
# ('eduardo', 'leticia')
# ('eduardo', 'fabricio')
# ('eduardo', 'moises')
# ('leticia', 'joao')
# ('leticia', 'jose')
# ('leticia', 'luiz')
# ('leticia', 'andre')
# ('leticia', 'eduardo')
# ('leticia', 'fabricio')
# ('leticia', 'moises')
# ('fabricio', 'joao')
# ('fabricio', 'jose')
# ('fabricio', 'luiz')
# ('fabricio', 'andre')
# ('fabricio', 'eduardo')
# ('fabricio', 'leticia')
# ('fabricio', 'moises')
# ('moises', 'joao')
# ('moises', 'jose')
# ('moises', 'luiz')
# ('moises', 'andre')
# ('moises', 'eduardo')
# ('moises', 'leticia')
# ('moises', 'fabricio')

# Produto:
# ('joao', 'joao')
# ('joao', 'jose')
# ('joao', 'luiz')
# ('joao', 'andre')
# ('joao', 'eduardo')
# ('joao', 'leticia')
# ('joao', 'fabricio')
# ('joao', 'moises')
# ('jose', 'joao')
# ('jose', 'jose')
# ('jose', 'luiz')
# ('jose', 'andre')
# ('jose', 'eduardo')
# ('jose', 'leticia')
# ('jose', 'fabricio')
# ('jose', 'moises')
# ('luiz', 'joao')
# ('luiz', 'jose')
# ('luiz', 'luiz')
# ('luiz', 'andre')
# ('luiz', 'eduardo')
# ('luiz', 'leticia')
# ('luiz', 'fabricio')
# ('luiz', 'moises')
# ('andre', 'joao')
# ('andre', 'jose')
# ('andre', 'luiz')
# ('andre', 'andre')
# ('andre', 'eduardo')
# ('andre', 'leticia')
# ('andre', 'fabricio')
# ('andre', 'moises')
# ('eduardo', 'joao')
# ('eduardo', 'jose')
# ('eduardo', 'luiz')
# ('eduardo', 'andre')
# ('eduardo', 'eduardo')
# ('eduardo', 'leticia')
# ('eduardo', 'fabricio')
# ('eduardo', 'moises')
# ('leticia', 'joao')
# ('leticia', 'jose')
# ('leticia', 'luiz')
# ('leticia', 'andre')
# ('leticia', 'eduardo')
# ('leticia', 'leticia')
# ('leticia', 'fabricio')
# ('leticia', 'moises')
# ('fabricio', 'joao')
# ('fabricio', 'jose')
# ('fabricio', 'luiz')
# ('fabricio', 'andre')
# ('fabricio', 'eduardo')
# ('fabricio', 'leticia')
# ('fabricio', 'fabricio')
# ('fabricio', 'moises')
# ('moises', 'joao')
# ('moises', 'jose')
# ('moises', 'luiz')
# ('moises', 'andre')
# ('moises', 'eduardo')
# ('moises', 'leticia')
# ('moises', 'fabricio')
# ('moises', 'moises')